{% set name = "tempora" %}
{% set version = "1.13" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4848df474c9d7ad9515fbeaadc88e48843176b4b90393652156ccff613bcaeb1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}


build:
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values

  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python
    - six
    - pytz
    - jaraco.functools >=1.20

test:
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
