{% set name = "tempora" %}
{% set version = "5.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e9606e65a3f2063460961d68515dee07bdaca0859305a8d3e6604168175fef1


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4.1
    - setuptools
  run:
    - python >={{ python_min }}
    - jaraco.functools >=1.20
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
