{% set name = "tempora" %}
{% set version = "1.12" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2b6dbb8402804840022e6f375bd86845e38eca5515e1c5c267ea137ee4f43978" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}


build:
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - six
    - pytz

test:
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
