{% set name = "tempora" %}
{% set version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98ee27bc528c91a236f9a5d612ede4ef391b01f7862bf11b483ce549053651c1


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values


requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python >=3.7
    - pytz
    - jaraco.functools >=1.20

test:
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
