{% set name = "tempora" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2bb51e2121976d931347b3e433917c364b83fdd5f64ef27336c865bf1fb0f75


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values


requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python >=3.7
    - pytz
    - jaraco.functools >=1.20

test:
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
