schema_version: 1

context:
  name: tempora
  version: 5.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 66e6ddee320c38f4b253a7d8039337424c699916451b9271e0ccce770a4e8f62

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - calc-prorate = tempora:calculate_prorated_values

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools_scm >=3.4.1
    - setuptools
  run:
    - python >=${{ python_min }}
    - jaraco.functools >=4.2
    - python-dateutil
    - jaraco.collections >=5.2.1
    - more-itertools
    - jaraco.context
tests:
  - python:
      imports:
        - tempora
      python_version: ${{ python_min }}.*
about:
  license_file: LICENSE
  license: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  homepage: https://github.com/jaraco/tempora
  repository: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
